### ISSUE TITLE
Refactor recursive builtin dict and list types to be generic type class factories

### ISSUE THREAD

**Issue by timburke** [iotile/typedargs#74]
The current implementation has a `Build` function that returns a type class.  We should use a similar method to have a Build function that returns a type class specialized for the generic parameter values as described in #70.

The goal should be that when we encounter a complex type we instantiate the corresponding concrete type class and use that instead.

**Comment by dvksirin** [comment]
@timburke 
It seems this issue does not require any extra changes in typedargs.
Complex types `Dict[t, t]` and `List[t]` are already mapped to our internal `map` and `list` types, these classes are used to instantiate required type objects.

**Comment by timburke** [comment]
Great, we can close this then.
